{{- if .Values.secrets.vso.configs }}
{{- if .Values.secrets.vso.configs.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "atlas.fullname" . }}-configs
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.secrets.vso.type }}
  mount: {{ .Values.secrets.vso.configs.engine }}
  path: {{ .Values.secrets.vso.configs.path }}
  destination: 
    name: {{ include "atlas.fullname" . }}-configs
    create: true
    overwrite: true
  refreshAfter: 1s 
  syncConfig:
    instantUpdates: false
  {{- if .Values.secrets.vso.configs.autorestart.enabled }}
  rolloutRestartTargets: 
  - kind: Deployment
    name: {{ include "atlas.fullname" . }}
  {{- end }}
  vaultAuthRef: {{ .Values.secrets.vso.vaultauth }}
{{- end }}
{{- end }}
---
{{- if .Values.secrets.vso.creds }}
{{- if .Values.secrets.vso.creds.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "atlas.fullname" . }}-creds
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.secrets.vso.type }}
  mount: {{ .Values.secrets.vso.creds.engine }}
  path: {{ .Values.secrets.vso.creds.path }}
  destination: 
    name: {{ include "atlas.fullname" . }}-creds
    create: true
    overwrite: true
  refreshAfter: 1s 
  syncConfig:
    instantUpdates: false
  {{- if .Values.secrets.vso.creds.autorestart.enabled }}
  rolloutRestartTargets: 
  - kind: Deployment
    name: {{ include "atlas.fullname" . }}
  {{- end }}
  vaultAuthRef: {{ .Values.secrets.vso.vaultauth }}
{{- end }}
{{- end }}

