{{- if .Values.secrets.creds }}
{{- if and .Values.secrets.creds.enabled (not .Values.secrets.vso.creds.enabled) (not .Values.secrets.vso.configs.enabled) }}
apiVersion: koudingspawn.de/v1
kind: Vault
metadata:
  name: {{ include "atlas.fullname" . }}-creds
  namespace: {{ .Values.namespace }}
  {{- with .Values.annotations.vault }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.secrets.creds.autorestart.enabled }}
  changeAdjustmentCallback:
    name: {{ include "atlas.fullname" . }}
    type: deployment
  {{- end }}
  path: {{ .Values.secrets.creds.path }}
  type: KEYVALUE
{{- end }}
{{- end }}
---
{{- if .Values.secrets.configs }}
{{- if and .Values.secrets.configs.enabled (not .Values.secrets.vso.creds.enabled) (not .Values.secrets.vso.configs.enabled) }}
apiVersion: koudingspawn.de/v1
kind: Vault
metadata:
  name: {{ include "atlas.fullname" . }}-configs
  namespace: {{ .Values.namespace }}
  {{- with .Values.annotations.vault }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.secrets.configs.autorestart.enabled }}
  changeAdjustmentCallback:
    name: {{ include "atlas.fullname" . }}
    type: deployment
  {{- end }}
  path: {{ .Values.secrets.configs.path }}
  type: KEYVALUE
{{- end }}
{{- end }}